import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

//*for my header to show up across my whole app, this is where I import the component
//the '@' is the import import alias - a simplified import - we can customise it if we want
import Header from "@/components/Header";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {/* children is a keyword that represents the content of all our pages */}
        {/* it's a placeholder */}
        {/* this is why we nest header above 'children' */}
        {children}
      </body>
    </html>
  );
}

